
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULDIVleftPOWrightUMINUSCLBRA DIV MINUS MUL NUMBER OPBRA PLUS POWinput : input line\n             | line : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression MUL expression\n                  | expression DIV expression\n                  | expression POW pow_expressionexpression : NUMBER\n                    | MINUS NUMBER %prec UMINUSpow_expression : MINUS NUMBER %prec UMINUSpow_expression : NUMBERexpression : OPBRA expression CLBRA'
    
_lr_action_items = {'NUMBER':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,],[-2,5,-1,-3,12,-9,5,5,5,5,5,20,-10,-4,-5,-6,-7,-8,22,-12,-13,-11,]),'MINUS':([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,],[-2,4,-1,8,-9,4,4,4,4,4,19,-10,8,-4,-5,-6,-7,-8,-12,-13,-11,]),'OPBRA':([0,1,2,3,5,6,7,8,9,10,12,14,15,16,17,18,20,21,22,],[-2,6,-1,-3,-9,6,6,6,6,6,-10,-4,-5,-6,-7,-8,-12,-13,-11,]),'$end':([0,1,2,3,5,12,14,15,16,17,18,20,21,22,],[-2,0,-1,-3,-9,-10,-4,-5,-6,-7,-8,-12,-13,-11,]),'PLUS':([3,5,12,13,14,15,16,17,18,20,21,22,],[7,-9,-10,7,-4,-5,-6,-7,-8,-12,-13,-11,]),'MUL':([3,5,12,13,14,15,16,17,18,20,21,22,],[9,-9,-10,9,9,9,-6,-7,-8,-12,-13,-11,]),'DIV':([3,5,12,13,14,15,16,17,18,20,21,22,],[10,-9,-10,10,10,10,-6,-7,-8,-12,-13,-11,]),'POW':([3,5,12,13,14,15,16,17,18,20,21,22,],[11,-9,-10,11,11,11,11,11,-8,-12,-13,-11,]),'CLBRA':([5,12,13,14,15,16,17,18,20,21,22,],[-9,-10,21,-4,-5,-6,-7,-8,-12,-13,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'line':([1,],[2,]),'expression':([1,6,7,8,9,10,],[3,13,14,15,16,17,]),'pow_expression':([11,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> input line','input',2,'p_input','lexer.py',108),
  ('input -> <empty>','input',0,'p_input','lexer.py',109),
  ('line -> expression','line',1,'p_line','lexer.py',113),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','lexer.py',120),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','lexer.py',121),
  ('expression -> expression MUL expression','expression',3,'p_expression_binop','lexer.py',122),
  ('expression -> expression DIV expression','expression',3,'p_expression_binop','lexer.py',123),
  ('expression -> expression POW pow_expression','expression',3,'p_expression_binop','lexer.py',124),
  ('expression -> NUMBER','expression',1,'p_expression_number','lexer.py',143),
  ('expression -> MINUS NUMBER','expression',2,'p_expression_number','lexer.py',144),
  ('pow_expression -> MINUS NUMBER','pow_expression',2,'p_pow_expression_minus','lexer.py',154),
  ('pow_expression -> NUMBER','pow_expression',1,'p_pow_expression_number','lexer.py',160),
  ('expression -> OPBRA expression CLBRA','expression',3,'p_expression_group','lexer.py',166),
]
